### ISSUE TITLE
Visualization in world space

### ISSUE THREAD

**Issue by cwule** [doughtmw/HoloLensForCV-Unity#4]
Wonderful project, with the Readme descriptions the build worked without a problem, thanks!

Two issues I am having:
- The app crashes on my Hololens quite often. Is that just for me or did you also experience that?
- Do you plan to visualize the depth information in world space instead of a screen?

**Comment by doughtmw** [comment]
Hi @cwule, I'm glad you were able to get the sample up and running! 

As to the issues you've described, I've experienced more crashes running the sample in Debug mode than the Release configuration. Also, the current implementation sends sensor frames from the C# Unity project to the C++ WinRT project every frame which is the likely cause of memory leaks and crashes. An alternative implementation would be to do all processing inside the C++ project and just return the final PvDepth frames.

I currently don't have plans to visualize the depth information in the world space instead of a screen, though I'd imagine it would be possible as all of the required transform matrices are easily accessible through the HoloLensForCV plugin. There are some discussions about visualizing depth in the world coordinate system on the [HoloLensForCV repo](https://github.com/microsoft/HoloLensForCV/issues/64) which could be of use!

**Comment by dbambulaks-labster** [comment]
@cwule have u managed to get it work in world space?

**Comment by kaiwu119** [comment]
@doughtmw @cwule 
I also encounter the situation that the app often crashes. I did it under the release version. Have you found the cause of the problem?

**Comment by cwule** [comment]
@quotetoxic @kaiwu119 I have not solved it, since I have moved to the HL2, with a very different research mode codebase.
